services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "${SA_PASSWORD}"
      # Or "Express" for lighter version
      MSSQL_PID: "Developer"
      # Use UTF-8 collation for full Unicode support and correct sorting
      MSSQL_COLLATION: Latin1_General_100_CI_AS_SC_UTF8
    ports:
      - "1433:1433"
    volumes:
      - sqlserver_data:/var/opt/mssql
    restart: unless-stopped

volumes:
  sqlserver_data:
